/* eslint-disable @next/next/no-img-element */
import classNames from "classnames";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Link from "next/link";

const Header: NextPage = () => {
  const [isShow, setIsShow] = useState(false);
  const [isSticky, setIsSticky] = useState(false);

  useEffect(() => {
    const onScroll = () => {
      if (window.scrollY > 0) {
        setIsSticky(true);
      } else {
        setIsSticky(false);
      }
    };
    window.addEventListener("scroll", onScroll);

    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const _toggle = () => {
    setIsShow((prevState) => !prevState);
  };

  const btnHamburgerClassName = classNames("header__toggle hide-for-desktop", {
    isShow,
  });

  const headerClassNames = classNames("header", { isSticky });

  const overlayClassNames = classNames(
    "overlay has-fade",
    isShow ? "fade-in" : "fade-out"
  );

  const menuMobileClassNames = classNames(
    "header__menu hide-for-desktop has-fade",
    isShow ? "fade-in" : "fade-out"
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={headerClassNames}>
        <div className={overlayClassNames} onClick={_toggle}></div>
        <nav className="header__main">
          <div className="container">
            <div className="header__main__nav">
              <div className="header__logo">
                <img src="/images/logo.svg" alt="" />
              </div>
              <div className={btnHamburgerClassName} onClick={_toggle}>
                <span></span>
                <span></span>
                <span></span>
              </div>
              <div className="header__link hide-for-mobile">
                <Link href="#">Home</Link>
                <Link href="#">About</Link>
                <Link href="#">Contact</Link>
                <Link href="#">Blog</Link>
                <Link href="#">Careers</Link>
              </div>
              <button className="btn btn--primary hide-for-mobile">
                Request Invite
              </button>
            </div>
          </div>
        </nav>
        <div className={menuMobileClassNames}>
          <Link href="#">Home</Link>
          <Link href="#">About</Link>
          <Link href="#">Contact</Link>
          <Link href="#">Blog</Link>
          <Link href="#">Careers</Link>
        </div>
      </header>
    </>
  );
};

export default Header;
